worker_processes  1;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    
    server {
      listen [::]:80;
      listen  80;
      server_name localhost;
      
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      gzip on; 
      gzip_vary on;
      gzip_min_length 1k;
      gzip_buffers 4 16k;
      gzip_comp_level 6;
      gzip_types  text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png image/x-icon;
      
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
} 
